services:

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  odoo:
    image: odoo:18.0
    depends_on:
      db:
        condition: service_healthy

    volumes:
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./document_expiry_engine:/mnt/extra-addons/document_expiry_engine

    environment:
      HOST: db
      PORT: 5432
      USER: odoo
      PASSWORD: odoo

