[options]
admin_passwd = $pbkdf2-sha512$600000$PUdISem9NwZACGHMeY/RWg$V5AH.N04XT47epA9io5Yl5x.vJwQ.A2Yz1Bshm2wVJ//oBtSsFptBFsFoLm2JczvvXFc1Klypm4s5snja0K9Pw
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
log_level = info

